language: node_js
node_js: 8.11.3 # LTS
sudo: false

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  repo: nukosuke/nukosuke.github.io
  target-branch: master
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master
